<center><img src="car.jpg" width=500></center>


Insurance companies invest a lot of time and money into optimizing their pricing and accurately estimating the likelihood that customers will make a claim. In many countries insurance it is a legal requirement to have car insurance in order to drive a vehicle on public roads, so the market is very large!

(`Source: https://www.accenture.com/_acnmedia/pdf-84/accenture-machine-leaning-insurance.pdf`) 

Knowing all of this, On the Road car insurance have requested your services in building a model to predict whether a customer will make a claim on their insurance during the policy period. As they have very little expertise and infrastructure for deploying and monitoring machine learning models, they've asked you to identify the single feature that results in the best performing model, as measured by accuracy, so they can start with a simple model in production.

They have supplied you with their customer data as a csv file called `car_insurance.csv`, along with a table detailing the column names and descriptions below.



## The dataset

| Column | Description |
|--------|-------------|
| `id` | Unique client identifier |
| `age` | Client's age: <br> <ul><li>`0`: 16-25</li><li>`1`: 26-39</li><li>`2`: 40-64</li><li>`3`: 65+</li></ul> |
| `gender` | Client's gender: <br> <ul><li>`0`: Female</li><li>`1`: Male</li></ul> |
| `driving_experience` | Years the client has been driving: <br> <ul><li>`0`: 0-9</li><li>`1`: 10-19</li><li>`2`: 20-29</li><li>`3`: 30+</li></ul> |
| `education` | Client's level of education: <br> <ul><li>`0`: No education</li><li>`1`: High school</li><li>`2`: University</li></ul> |
| `income` | Client's income level: <br> <ul><li>`0`: Poverty</li><li>`1`: Working class</li><li>`2`: Middle class</li><li>`3`: Upper class</li></ul> |
| `credit_score` | Client's credit score (between zero and one) |
| `vehicle_ownership` | Client's vehicle ownership status: <br><ul><li>`0`: Does not own their vehilce (paying off finance)</li><li>`1`: Owns their vehicle</li></ul> |
| `vehcile_year` | Year of vehicle registration: <br><ul><li>`0`: Before 2015</li><li>`1`: 2015 or later</li></ul> |
| `married` | Client's marital status: <br><ul><li>`0`: Not married</li><li>`1`: Married</li></ul> |
| `children` | Client's number of children |
| `postal_code` | Client's postal code | 
| `annual_mileage` | Number of miles driven by the client each year |
| `vehicle_type` | Type of car: <br> <ul><li>`0`: Sedan</li><li>`1`: Sports car</li></ul> |
| `speeding_violations` | Total number of speeding violations received by the client | 
| `duis` | Number of times the client has been caught driving under the influence of alcohol |
| `past_accidents` | Total number of previous accidents the client has been involved in |
| `outcome` | Whether the client made a claim on their car insurance (response variable): <br><ul><li>`0`: No claim</li><li>`1`: Made a claim</li></ul> |

In [60]:
# Import required modules
import pandas as pd
import numpy as np
from statsmodels.formula.api import logit

# 1. Reading in and exploring the dataset

In [61]:
df = pd.read_csv('car_insurance.csv')
df.head()

       id  age  gender  ... duis past_accidents outcome
0  569520    3       0  ...    0              0     0.0
1  750365    0       1  ...    0              0     1.0
2  199901    0       0  ...    0              0     0.0
3  478866    0       1  ...    0              0     0.0
4  731664    1       1  ...    0              1     1.0

[5 rows x 18 columns]

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   10000 non-null  int64
 1   age                  10000 non-null  int64
 2   gender               10000 non-null  int64
 3   driving_experience   10000 non-null  object
 4   education            10000 non-null  object
 5   income               10000 non-null  object
 6   credit_score         9018 non-null   float64
 7   vehicle_ownership    10000 non-null  float64
 8   vehicle_year         10000 non-null  object
 9   married              10000 non-null  float64
 10  children             10000 non-null  float64
 11  postal_code          10000 non-null  int64
 12  annual_mileage       9043 non-null   float64
 13  vehicle_type         10000 non-null  object
 14  speeding_violations  10000 non-null  int64
 15  duis                 10000 non-null  int64
 16  past_accidents       10000 non-null  int64
 17  outcome              10000 non-null  float64
dtypes: float64(6), int64(7), object(5)
memory usage: 1.4+ MB

In [63]:
df.describe()

                  id           age  ...  past_accidents       outcome
count   10000.000000  10000.000000  ...    10000.000000  10000.000000
mean   500521.906800      1.489500  ...        1.056300      0.313300
std    290030.768758      1.025278  ...        1.652454      0.463858
min       101.000000      0.000000  ...        0.000000      0.000000
25%    249638.500000      1.000000  ...        0.000000      0.000000
50%    501777.000000      1.000000  ...        0.000000      0.000000
75%    753974.500000      2.000000  ...        2.000000      1.000000
max    999976.000000      3.000000  ...       15.000000      1.000000

[8 rows x 13 columns]

# 2. Filling missing value

In [64]:
# Finding how many missing values are there
df.isna().sum()

id                       0
age                      0
gender                   0
driving_experience       0
education                0
income                   0
credit_score           982
vehicle_ownership        0
vehicle_year             0
married                  0
children                 0
postal_code              0
annual_mileage         957
vehicle_type             0
speeding_violations      0
duis                     0
past_accidents           0
outcome                  0
dtype: int64

### The missing values are:

In [65]:
missing_values = df[df.isna().any(axis=1)]

In [66]:
# Replacing the missing values with the mean of the respective column
df.fillna(df.mean(),inplace=True)
# Checking if there are still missing values
df.isna().sum()

id                     0
age                    0
gender                 0
driving_experience     0
education              0
income                 0
credit_score           0
vehicle_ownership      0
vehicle_year           0
married                0
children               0
postal_code            0
annual_mileage         0
vehicle_type           0
speeding_violations    0
duis                   0
past_accidents         0
outcome                0
dtype: int64

# 3. Preparing for modeling

In [67]:
# Creating an empty list of models
models = []

# Create features that contain all columns except for response variable
features = df.columns.drop(['outcome','id'])
features

Index(['age', 'gender', 'driving_experience', 'education', 'income',
       'credit_score', 'vehicle_ownership', 'vehicle_year', 'married',
       'children', 'postal_code', 'annual_mileage', 'vehicle_type',
       'speeding_violations', 'duis', 'past_accidents'],
      dtype='object')

# 4. Building and storing the models

In [68]:
def build_models(features):
    for feature in features:
        model = logit(f'outcome ~ {feature}',data= df).fit()
        models.append(model)
        
build_models(features)

Optimization terminated successfully.
         Current function value: 0.511794
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.615951
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.467092
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.603742
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.531499
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.572557
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.552412
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.572668
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.586659
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.595431
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.617345
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.605716
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.621700
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.558922
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.598699
         Iterations 6
Optimization terminated successfully.
         Current function value: 0.549220
         Iterations 7

In [69]:
# Sanity check, make sure there are 16 models after removing 'outcome' and 'id'
num_models = len(models)
num_models

16

# 5. Measuring performance

In [70]:
# Creating a list for accuracy scores and set the confusion matrix
accuracies = []

# Create confusion matrix with each model and calculate accruracy
def model_accuracy(models):
    for model in models:
        conf_matrix = model.pred_table()
        TN = conf_matrix[0,0]
        FP = conf_matrix[0,1]
        FN = conf_matrix[1,0]
        TP = conf_matrix[1,1]
        accuracy = (TN+TP)/(TN+FP+FN+TP)
        accuracies.append(accuracy)
        
model_accuracy(models)
print(confusion_matrices)

[array([[6299.,  568.],
       [1685., 1448.]]), array([[6867.,    0.],
       [3133.,    0.]]), array([[5554., 1313.],
       [ 916., 2217.]]), array([[6867.,    0.],
       [3133.,    0.]]), array([[6239.,  628.],
       [1947., 1186.]]), array([[6321.,  546.],
       [2400.,  733.]]), array([[5594., 1273.],
       [1376., 1757.]]), array([[6867.,    0.],
       [3133.,    0.]]), array([[6867.,    0.],
       [3133.,    0.]]), array([[6867.,    0.],
       [3133.,    0.]]), array([[6867.,    0.],
       [3133.,    0.]]), array([[6801.,   66.],
       [3030.,  103.]]), array([[6867.,    0.],
       [3133.,    0.]]), array([[6867.,    0.],
       [3133.,    0.]]), array([[6867.,    0.],
       [3133.,    0.]]), array([[6867.,    0.],
       [3133.,    0.]])]

In [71]:
print(accuracies)

[0.7747, 0.6867, 0.7771, 0.6867, 0.7425, 0.7054, 0.7351, 0.6867, 0.6867, 0.6867, 0.6867, 0.6904, 0.6867, 0.6867, 0.6867, 0.6867]

# 6. Finding the best performing model

In [72]:
# Finding the best feature and highest accuracy
best_feature = features[accuracies.index(max(accuracies))]
best_accuracy = max(accuracies)

print(f'The best feature is {best_feature} with an accuracy of {best_accuracy}')

The best feature is driving_experience with an accuracy of 0.7771

In [73]:
# Creating the dataframe of best feature and accuracy
best_feature_df = pd.DataFrame({'best_feature': [best_feature], 
                                'best_accuracy': [best_accuracy]})

best_feature_df

         best_feature  best_accuracy
0  driving_experience         0.7771